version: '3.1'

services:
  mongo:
    container_name: ebook-mongoDB
    image: mongo:4.4
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongoDb
      # MONGO_INITDB_ROOT_PASSWORD: password123
      # MONGO_INITDB_DATABASE: ebook
      # MONGODB_DATABASE: ebook
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
   

 
  
volumes:
  mongodb:
    name: mongodb-ebook

